### ISSUE TITLE
[Documentation] Create a documentation file to validate the roadmap of service

### ISSUE THREAD

**Issue by WhiteAngel13** [infinity-js/gandalf#1]
- [x] Create a documentation file
- [x] Document the gandalf roadmap
- [x] Implements the new issues for milestone

**Comment by WhiteAngel13** [comment]
https://github.com/infinity-js/gandalf/wiki/01-%E2%80%90-Concepts

**Comment by WhiteAngel13** [comment]
https://github.com/infinity-js/gandalf/issues/2
